global:
  scrape_interval:     5s
  evaluation_interval: 5s

# Load Rules
rule_files:
  - "alert.rules"

# Scrape Endpoints
scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'c-advisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['c-advisor:8080']
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']