{
 "title": "C > Docker and System Monitoring",
 "description": "Custom > A dashboard for visualizing Docker utilization system-wide as well as per container.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Container Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Active Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) / sum(rate(node_cpu_seconds_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "System RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_Active_bytes / node_memory_MemTotal_bytes)\n"
    }
   ]
  },
  {
   "title": "System Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)\n"
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Docker CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval]))/sum(machine_cpu_cores) * 100",
     "legendFormat": "Docker CPU Usage"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) - sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])))/sum(machine_cpu_cores) * 100",
     "legendFormat": "System CPU Usage"
    }
   ]
  },
  {
   "title": "Docker RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"})/sum(node_memory_MemTotal_bytes) * 100\n",
     "legendFormat": "Docker RAM Usage"
    },
    {
     "expr": "(sum(node_memory_Active_bytes))/sum(node_memory_MemTotal_bytes) * 100\n",
     "legendFormat": "System RAM Usage"
    }
   ]
  },
  {
   "title": "Docker CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "c" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "Docker CPU Usage"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) - sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "System CPU Usage"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Docker RAM Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"})",
     "legendFormat": "Docker RAM Usage"
    },
    { "expr": "sum(node_memory_Active_bytes)", "legendFormat": "System RAM Usage" },
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Container (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance,name) (\n    label_replace(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval]), \"instance\", \"cadvisor\", \"instance\", \".*cadvisor.*\")\n) / on (instace) group_left() sum by (instance) (\n    label_replace(machine_cpu_cores, \"instance\", \"cadvisor\", \"instance\", \".*cadvisor.*\")\n) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM Usage per Container (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)  / on () group_left() sum by (instance) (sum(node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "c" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    },
    { "expr": "sum(machine_cpu_cores{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Usage per Container (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$__rate_interval])) by (name) * 8",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$__rate_interval])) by (name) * 8",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\".+\"} - container_memory_usage_bytes{name=~\".+\"})  * 100 / container_spec_memory_limit_bytes{name=~\".+\"}) ) by (name) ",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name) ",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\"}) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}